[package]
name = "exclusion_check_issuing_country"
type = "bin"
authors = ["Theo Madzou"]
compiler_version = ">=0.22.0"

[dependencies]
exclusion_check_country = { path = "../../../../lib/exclusion-check/country" }
commitment = { path = "../../../../lib/commitment/scoped-nullifier" }
utils = { path = "../../../../lib/utils" }
