[package]
name = "sig_check_dsc_rsa_pss_2048"
type = "bin"
authors = ["Theo Madzou"]
compiler_version = ">=0.36.0"

[dependencies]
sig_check_rsa = { path = "../../../../../../lib/sig-check/rsa" }
utils = { path = "../../../../../../lib/utils" }