[package]
name = "compare_birthdate_evm"
type = "bin"
authors = ["Theo Madzou", "Michael Elliot"]
compiler_version = ">=1.0.0"

[dependencies]
compare_date_lib = { path = "../../../../lib/compare/date" }
commitment = { path = "../../../../lib/commitment/scoped-nullifier" }