[package]
name = "bind_evm"
type = "bin"
authors = ["Theo Madzou", "Michael Elliot"]
compiler_version = ">=1.0.0"

[dependencies]
bind = { path = "../../../lib/bind" }
commitment = { path = "../../../lib/commitment/scoped-nullifier" }
