[package]
name = "inclusion_check_nationality_evm"
type = "bin"
authors = ["Theo Madzou"]
compiler_version = ">=0.22.0"

[dependencies]
inclusion_check_country = { path = "../../../../lib/inclusion-check/country" }
commitment = { path = "../../../../lib/commitment/scoped-nullifier" }
utils = { path = "../../../../lib/utils" }
