[profile.default]
src = "src"
out = "out"
libs = ["lib"]
# Enable the optimizer
optimizer = true
optimizer_runs = 200
fs_permissions = [{ access = "read-write", path = "./"}]

# Ethereum Sepolia configuration
[rpc_endpoints]
anvil = "http://127.0.0.1:8545"
sepolia = "${SEPOLIA_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"

# Etherscan configuration
# The API key is only needed for Sepolia deployments with verification
# For local deployments, this section is not used
[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }
mainnet = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
