[package]
name = "sig_check_dsc_rsa_pss_4096"
type = "bin"
authors = ["Theo Madzou"]
compiler_version = ">=0.36.0"

[dependencies]
sig_check_rsa = { path = "../../../../../../lib/sig-check/rsa" }
commitment = { path = "../../../../../../lib/commitment/csc-to-dsc" }
