[package]
name = "sig_check_dsc_tbs_1200_rsa_pss_1024"
type = "bin"
authors = ["Theo Madzou", "Michael Elliot"]
compiler_version = ">=0.36.0"

[dependencies]
sig_check_rsa = { path = "../../../../../../../lib/sig-check/rsa" }
utils = { path = "../../../../../../../lib/utils" }
commitment = { path = "../../../../../../../lib/commitment/csc-to-dsc" }
